In [1]:
import numpy as np

l=[i for i in range(100)]
pr(l)

n=np.arange(100)
pr(n)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [2]:
print(n.itemsize)
print(n.itemsize*n.size)

4
400


In [3]:
import sys
a=10
print(sys.getsizeof(a))
print(sys.getsizeof(1)*len(l))

28
2800


In [4]:
import time
import numpy as np

size=100000

def listpy():
    t1=time.time()
    a=range(size)
    b=range(size)
    c=[a[i]+b[i] for i in range(size)]
    t2=time.time()
    print((t2-t1)*1000)
    
def numpy():
    t1=time.time()
    a=np.arange(size)
    b=np.arange(size)
    c=a+b
    t2=time.time()
    print((t2-t1)*1000)
    
listpy()
numpy()

40.891408920288086
1.547098159790039


In [5]:
import numpy as np

b=[1,2,3]
print(b)
c=np.array(b)
print(c)
print(type(c))

[1, 2, 3]
[1 2 3]
<class 'numpy.ndarray'>


In [6]:
b=[1,2,3,'5','A',1.245]
print(b)
c=np.array(b)
print(c)
print(type(c))

[1, 2, 3, '5', 'A', 1.245]
['1' '2' '3' '5' 'A' '1.245']
<class 'numpy.ndarray'>


In [7]:
b=[1,2,3,'5',1.245]
c=np.array(b,dtype=float)
print(c)

[1.    2.    3.    5.    1.245]


In [8]:
b=[1,2,3,'5',1.245]
c=np.array(b*3)
print(c)

['1' '2' '3' '5' '1.245' '1' '2' '3' '5' '1.245' '1' '2' '3' '5' '1.245']


In [9]:
b=np.ones(10) #b=np.ones(3,dtype=int)
print(b)
c=np.ones((2,3),dtype=int)
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [10]:
b=np.zeros(3,dtype=int)
print(b)
c=np.zeros((4,6))
print(c)

[0 0 0]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
b=np.full(3,4) #size, element
print(b)
c=np.full(3,4,dtype=str)
print(c)
d=np.full((2,3),50,dtype=float)
print(d)

[4 4 4]
['4' '4' '4']
[[50. 50. 50.]
 [50. 50. 50.]]


In [12]:
b=np.empty(3) #size
print(b)
c=np.empty(5,dtype=int)
print(c)
d=np.empty((2,8),dtype=str)
print(d)

[0. 0. 0.]
[-350754864        354          0          0     131074]
[['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']]


In [13]:
b=np.arange(10)
print(b)
c=np.arange(2,10)
print(c)
d=np.arange(2,10,2)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]


In [14]:
#linspace takes step value by its own
b=np.linspace(2,10) #start,end
print(b)
print(b[1]-b[0]) #step value
print(b[4]-b[3])

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]
0.16326530612244916
0.16326530612244872


In [15]:
b=np.linspace(2,10,5,dtype=int) #start,end,size, here both 2 and 10 are inclusive
print(b)
c=np.linspace(2,10,5,dtype=int,endpoint=False) #start,end,size, here endpoint is false, so 10 is exclusive
print(c)
d=np.linspace(2,10,7,dtype=int,endpoint=False) 
print(d)

[ 2  4  6  8 10]
[2 3 5 6 8]
[2 3 4 5 6 7 8]


In [16]:
b=np.identity(3) #here only one argument can be passed to generate n*n matrx
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
b=np.eye(3)
print(b)
c=np.eye(3,4)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [18]:
b=np.random.rand(3)
print(b)
c=np.random.rand(3,4)
print(c)

[0.05688725 0.21889901 0.76020367]
[[0.75489351 0.45535537 0.05101894 0.69997838]
 [0.94521324 0.45310808 0.32299317 0.00439255]
 [0.87848613 0.40406135 0.94435614 0.12069518]]


In [19]:
d=np.random.rand(10)*10
print(d)

[9.19912045 8.00435252 3.27616008 7.94204878 7.77615667 6.61808859
 2.64708379 8.50722282 2.38910174 3.28572374]


In [20]:
b=np.random.randint(10)
print(b)
c=np.random.randint(2,10,(10,1))
print(c)

2
[[7]
 [6]
 [3]
 [8]
 [8]
 [4]
 [7]
 [7]
 [4]
 [2]]


In [21]:
#1D

b=[1,2,3,4,5]
c=np.array(b)

print(c)
print(c.data)
print(c.shape)
print(c.strides)
print(c[3])
print(c[1:4])

[1 2 3 4 5]
(5,)
(4,)
4
[2 3 4]


In [22]:
#2D

b=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
c=np.array(b)
print(b)
print(c)
print(c.data) #memory pointing to first element
print(c.shape) #size of the numpy array
print(c.strides) #no of bytes need to move to next element
print(b[2][2]) #here b[2,2] will not work as it is not numpy array
print(c[2][2])
print(c[2,2]) # row,col
print(b[1][:3]) #similary here also b[1,:3] will not work
print(c[1][:3])
print(c[1,:3])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
(16, 4)
11
11
11
[5, 6, 7]
[5 6 7]
[5 6 7]


In [23]:
#now if we want to print [3,7,11]= > col=2 and row 0 to 2, we have to use for loop to get the elements
print(b[0:3][2])

x=b[0:3]
print(x)
y=x[2]
print(y)

[9, 10, 11, 12]
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [24]:
print(c[:3,2])
print(c[:3][2])

[ 3  7 11]
[ 9 10 11 12]


In [25]:
# to get [[10,11],
#            [14,15]]

print(b[2:4][1:3])

print(b[2:4])
print(b[2:4][1:3])

[[13, 14, 15, 16]]
[[9, 10, 11, 12], [13, 14, 15, 16]]
[[13, 14, 15, 16]]


In [26]:
print(c[2:4,1:3])
print(c[2:4][1:3])

[[10 11]
 [14 15]]
[[13 14 15 16]]


In [27]:
l=[1,2,3,4,5]

print(l)

c=np.random.randint(1,20,10)
d=np.random.randint(1,20,10)

print(c)
print(d)

[1, 2, 3, 4, 5]
[18 17 14 11 11  7  6 16  1  5]
[12 19  2  1  5 16  3  8 18  9]


In [28]:
l=[i+1 for i in l]
print(l)

c+=1
print(c)

[2, 3, 4, 5, 6]
[19 18 15 12 12  8  7 17  2  6]


In [29]:
print(c+d)
print(c-d)
print(c*d)
print(c/d)
print(c//d)
print(c**d)

[31 37 17 13 17 24 10 25 20 15]
[  7  -1  13  11   7  -8   4   9 -16  -3]
[228 342  30  12  60 128  21 136  36  54]
[ 1.58333333  0.94736842  7.5        12.          2.4         0.5
  2.33333333  2.125       0.11111111  0.66666667]
[ 1  0  7 12  2  0  2  2  0  0]
[-1987646927  -355991552         225          12      248832           0
         343 -1614177151      262144    10077696]


In [30]:
print(c)
print(c.sum())
print(c.mean())
print(c.min())
print(c.argmin()) #gives the index of the first minimum element
print(c.max())
print(c.argmax()) #gives the index of the first max element

[19 18 15 12 12  8  7 17  2  6]
116
11.6
2
8
19
0


In [31]:
print(c)
print(d)
print(c>d)
print(c<d)
print(c==d)

[19 18 15 12 12  8  7 17  2  6]
[12 19  2  1  5 16  3  8 18  9]
[ True False  True  True  True False  True  True False False]
[False  True False False False  True False False  True  True]
[False False False False False False False False False False]


In [32]:
c[2]=0
print(c)
print(d)
print(np.logical_or(c,d))
print(np.logical_and(c,d))
print(np.logical_not(c))

[19 18  0 12 12  8  7 17  2  6]
[12 19  2  1  5 16  3  8 18  9]
[ True  True  True  True  True  True  True  True  True  True]
[ True  True False  True  True  True  True  True  True  True]
[False False  True False False False False False False False]


In [33]:
b=[[1,2,3,4],[5,6,15,80],[9,10,11,12],[13,14,15,16]]
d=[[0,1,2,3],[10,12,16,18],[-10,9,8,7],[11,45,78,90]]
e=np.array(b)
f=np.array(d)
print(e)
print(e.sum())
print(e.mean())
print(e.max())
print(e.argmax()) #it treats 2d array as 1d array and return index wrt it
print(e.min())
print(e.argmin())

[[ 1  2  3  4]
 [ 5  6 15 80]
 [ 9 10 11 12]
 [13 14 15 16]]
216
13.5
80
7
1
0


In [34]:
print(e)
print(f)
print()
print(e>f)
print()
print(e<f)
print()
print(e==f)
print()
print(np.logical_or(e,f))
print()
print(np.logical_and(e,f))

[[ 1  2  3  4]
 [ 5  6 15 80]
 [ 9 10 11 12]
 [13 14 15 16]]
[[  0   1   2   3]
 [ 10  12  16  18]
 [-10   9   8   7]
 [ 11  45  78  90]]

[[ True  True  True  True]
 [False False False  True]
 [ True  True  True  True]
 [ True False False False]]

[[False False False False]
 [ True  True  True False]
 [False False False False]
 [False  True  True  True]]

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [35]:
import numpy as np
#boolean idnexing
b=np.array(['w','b','h','s','r','a','a','k','v','a'])
c=np.random.randint(1,20,10)

print(b)
print(c)

['w' 'b' 'h' 's' 'r' 'a' 'a' 'k' 'v' 'a']
[16  4 18  6  8  5  3  4 17  4]


In [36]:
bool_arr=c>10
print(bool_arr)
new_arr=c[bool_arr]
print(new_arr)

[ True False  True False False False False False  True False]
[16 18 17]


In [37]:
print(c[c>10])
print(c[(c>10) & (c<18)])

[16 18 17]
[16 17]


In [38]:
print(c)

[16  4 18  6  8  5  3  4 17  4]


In [39]:
c[:3]=9
print(c)

[ 9  9  9  6  8  5  3  4 17  4]


In [40]:
c[c>10]=100
print(c)

[  9   9   9   6   8   5   3   4 100   4]


In [41]:
print(c)
print(c[c==100])

[  9   9   9   6   8   5   3   4 100   4]
[100]


In [42]:
print(c)
ind=np.where(c==100)
print(ind)

[  9   9   9   6   8   5   3   4 100   4]
(array([8], dtype=int64),)


In [43]:
print(b)
print(c)
ind=np.where(c==100)
print(ind)
print(b[ind])

['w' 'b' 'h' 's' 'r' 'a' 'a' 'k' 'v' 'a']
[  9   9   9   6   8   5   3   4 100   4]
(array([8], dtype=int64),)
['v']


In [44]:
#boolean indexing on 2d
b=np.random.randint(1,30,(5,6))
print(b)
print(b>20)

[[19  7 14 14 14  8]
 [23 19 19 23 15  4]
 [15 29 11 28  6  5]
 [11 19 17 23  2 25]
 [ 9 17 26 14 21 16]]
[[False False False False False False]
 [ True False False  True False False]
 [False  True False  True False False]
 [False False False  True False  True]
 [False False  True False  True False]]


In [45]:
print(b[b>20]) #ans in 1d array

[23 23 29 28 23 25 26 21]


In [46]:
b[b>20]=100
print(b)

[[ 19   7  14  14  14   8]
 [100  19  19 100  15   4]
 [ 15 100  11 100   6   5]
 [ 11  19  17 100   2 100]
 [  9  17 100  14 100  16]]


In [47]:
print(b)
print()
bool_arr=b[:,3]==100
print(bool_arr)
print()
b[bool_arr,3]=90
print(b)

[[ 19   7  14  14  14   8]
 [100  19  19 100  15   4]
 [ 15 100  11 100   6   5]
 [ 11  19  17 100   2 100]
 [  9  17 100  14 100  16]]

[False  True  True  True False]

[[ 19   7  14  14  14   8]
 [100  19  19  90  15   4]
 [ 15 100  11  90   6   5]
 [ 11  19  17  90   2 100]
 [  9  17 100  14 100  16]]


In [48]:
print(b[:,1].argsort())
ind=b[:,1].argsort()
print(b[ind])

[0 4 1 3 2]
[[ 19   7  14  14  14   8]
 [  9  17 100  14 100  16]
 [100  19  19  90  15   4]
 [ 11  19  17  90   2 100]
 [ 15 100  11  90   6   5]]


In [49]:
print(b[0,:].argsort())
ind=b[0,:].argsort()
#print(ind)
#print(b[:,ind])

[1 5 2 3 4 0]


In [50]:
#broadcasting

import numpy as np

x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print(y)

[[3 5 7]
 [7 9 8]
 [7 7 9]]
[[1 2 4]
 [4 5 3]
 [3 4 6]]


In [51]:
print(x+y)

[[ 4  7 11]
 [11 14 11]
 [10 11 15]]


In [52]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,3)
print(x)
print(y)

[[3 4 1]
 [5 6 6]
 [5 2 1]]
[5 4 9]


In [53]:
print(x-y)

[[-2  0 -8]
 [ 0  2 -3]
 [ 0 -2 -8]]


In [54]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(2,3))

#print(x-y) error because of diff in size

y=np.transpose(y)
print(x-y)

[[-3  7]
 [ 1  8]
 [ 2 -1]]


In [55]:
x=np.random.randint(1,10,6)
print(x)
y=x.resize(2,1)
print(x)
print(y)
#here it can be resized to anything, if elements are missing then they are filled with zeros. The original array is changed.

[6 9 9 5 1 9]
[[6]
 [9]]
None


In [56]:
x=np.random.randint(1,10,6)
print(x)
y=x.reshape(6,1)
print(x)
print(y)
#Here, it can only be resized to the multiples of m*n. The original array is not changed.

[3 2 2 1 8 4]
[3 2 2 1 8 4]
[[3]
 [2]
 [2]
 [1]
 [8]
 [4]]
